apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-app2-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx # must be the same
  rules:
    - host: app2.local # your DNS
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-app2-service
                port:
                  number: 80
