apiVersion: v1
kind: Service
metadata:
  name: fastapi-app2-service
  labels:
    app: fastapi-app2
spec:
  selector:
    app: fastapi-app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
